import { K2D } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
const inter = K2D({ weight: '400', subsets: ["latin"] });
// const k2D = K2D({ weight: '400', subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      {/* <body className={`flex flex-col items-center justify-center px-[7.5%] ${inter.className}`}> */}
      {/* <Header /> */}
        {/* <Heade /> */}
        {children}</body>
    </html>
  );
}
